language: bash

services:
  - docker

os: linux
dist: xenial

env:
  global:
    - CRAWLER_TAG=v0.1.0
    - KEEPER_TAG=v0.1.0
    - PLANNER_TAG=v0.1.0
    - MODULE_TARGET=x86_64-unknown-linux-musl

jobs:
  fast_finish: true
  include:
    - env:
        - MODULE_NAME=crawler
        - MODULE_TAG=${CRAWLER_TAG}
    - env:
        - MODULE_NAME=keeper
        - MODULE_TAG=${KEEPER_TAG}
    - env:
        - MODULE_NAME=planner
        - MODULE_TAG=${PLANNER_TAG}

before_script:
  - set -e

script:
  - >
    docker build -t crawlis/${MODULE_NAME}-${MODULE_TAG}-debug
    --build-arg MODULE_NAME=${MODULE_NAME}
    --build-arg MODULE_TAG=${MODULE_TAG}
    --build-arg MODULE_TARGET=${MODULE_TARGET}
    -f ./dockerfiles/generic-module-debug.Dockerfile .
  - >
    docker build -t crawlis/${MODULE_NAME}-${MODULE_TAG}
    --build-arg MODULE_NAME=${MODULE_NAME}
    --build-arg MODULE_TAG=${MODULE_TAG}
    --build-arg MODULE_TARGET=${MODULE_TARGET}
    -f ./dockerfiles/generic-module-release.Dockerfile .

after_script:
  - set +e

before_deploy:
  - echo ${DOCKERHUB_ACCESS_TOKEN} | docker login --username crawlis --password-stdin

deploy:
  provider: script
  script: docker push crawlis/${MODULE_NAME}-${MODULE_TAG}-debug && docker push crawlis/${MODULE_NAME}-${MODULE_TAG}
  on:
    repo: crawlis/captain
    tags: true

branches:
  only:
    - master
    # Regex pattern to match tags
    - /^v\d+\.\d+\.\d+.*$/
