version: "3.7"
services:
  crawler:
    build:
      context: ../crawler
      dockerfile: ./dockerfiles/local-module-debug.Dockerfile
    environment:
      - NATS_URI=nats://nats:4222
      - STARTING_URL=https://lemonde.fr
    depends_on:
      - nats

  nats:
    image: "nats"
    expose:
      - "4222"
    ports:
      - "8222:8222"

  keeper:
    build:
      context: ../keeper
      dockerfile: ./dockerfiles/local-module-debug.Dockerfile
    env_file: ../keeper/.env
    environment:
      - NATS_URI=nats://nats:4222
      - DATABASE_URI=postgresql://postgres:password@keeper-db/keeper
    depends_on:
      - nats
      - keeper-db

  keeper-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keeper
    ports:
      - "5432:5432"
    restart: unless-stopped
