version: "3.7"
services:
  crawler:
    build:
      context: ../crawler
      dockerfile: ./dockerfiles/local-module-debug.Dockerfile
    environment:
      - NATS_URI=nats://nats:4222
      - STARTING_URL=https://lemonde.fr
    depends_on:
      - nats

  keeper:
    build:
      context: ../keeper
      dockerfile: ./dockerfiles/local-module-debug.Dockerfile
    environment:
      - NATS_URI=nats://nats:4222
      - DATABASE_URI=postgresql://postgres:password@database/keeper
    depends_on:
      - nats
      - database

  planner:
    build:
      context: ../planner
      dockerfile: ./dockerfiles/local-module-debug.Dockerfile
    environment:
      - NATS_URI=nats://nats:4222
      - DATABASE_URI=postgresql://postgres:password@database/keeper
      - STARTING_URL=https://lemonde.fr
    depends_on:
      - nats
      - database

  nats:
    image: "nats"
    ports:
      - "8222:8222"
    restart: unless-stopped

  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keeper
    ports:
      - "5432:5432"
    restart: unless-stopped
