version: "3.7"
services:
  crawler:
    build:
      context: .
      args:
        - MODULE_NAME=crawler
        - MODULE_TAG=v0.0.1
    depends_on:
      - keeper

  keeper:
    build:
      context: .
      args:
        - MODULE_NAME=keeper
        - MODULE_TAG=v0.0.1
    ports:
      - 3030:3030
