version: "3.7"
services:
  crawler:
    build:
      context: .
      dockerfile: ./dockerfiles/module-debug.Dockerfile
      args:
        - MODULE_NAME=crawler
        - MODULE_TAG=v0.0.1
        - MODULE_TARGET=x86_64-unknown-linux-musl
    environment:
      - KEEPER_HOST=keeper
      - KEEPER_PORT=3030
      - STARTING_URL=https://lemonde.fr
      - MAX_RETRIES=10
    depends_on:
      - keeper
    restart: unless-stopped

  keeper:
    build:
      context: .
      dockerfile: ./dockerfiles/module-debug.Dockerfile
      args:
        - MODULE_NAME=keeper
        - MODULE_TAG=v0.0.1
        - MODULE_TARGET=x86_64-unknown-linux-musl
    environment:
      - SERVER_PORT=3030
